### ISSUE TITLE
Problem with mpd Music Player Daemon 0.19.15

### ISSUE THREAD

**Issue by aznowicz** [hzeller/folve#1] opened 2016-05-03 22:41 UTC
Hello,

I'm trying to setup folve with Archlinux and i'm facing a strange problem with mpd.
With any playlist with flac titles, when a song lasts, mpd fails to jump to the next song and eats all my CPU at 100%.
Issuing a "mpc next" forces the next song in the playlist to be played, until that one ends...
There is no problem playing those songs directly with folve disabled. 
Tried 2 different kernel with same issue (running stock-archlinux kernel 4.5 or linux-rt-3.18.29-rt30-1-rt-lts)
Tried with 2 different mpd versions (latest 0.19.15 and previous one)
Tried with local-storage instead of NFS
Tried with gapless enabled or disabled with no change.

dmesg, journalctl don't show any message to help investigate. Just mpd going crazy.

Here is how folve is started :+1: sudo -u mpd /usr/bin/folve -O 2.7 -D -b -1 -p 8081 -C /etc/folve/KodiHifi /mnt/nfs/Musique /mnt/folve

If you have any idea to point me to the right direction...

Thank you! 

*_mpd.conf = *_
log_level "verbose"
pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory "/mnt/folve"
zeroconf_name   "Salon Hifi"
audio_output {
        type    "alsa"
        name    "NVidia"
        device  "hw:0,7"
        mixer_type "none"
        auto_resample "no"
}

**Comment by hzeller** [comment] 2016-05-03 23:18
Is it mpd eating all the CPU or folve ? I could imagine that mpd attempts to jump to almost the end of a file do do something like gapless playing. Or it does some other wierd seek operation that folve answers by convolving to the point where it seeks. And of course, in that case, it might search all the way to the end. You can see what folve is doing in these times by looking at the web status page (see description in the README).

If it is indeed mpd that runs into CPU trouble, then I could imagine that it might try an operation on the filesystem that is not implemented; folve only supports the operations typically needed for reading the files, but no operation such as changing permissions for instance. Maybe it gets into some weird loop then ?

To test that, I would suggest to run `mpd` using `strace`

  `strace -o /tmp/mpd-strace.log mpd [arguments to mpd]`

then, when it runs into the problem you can inspect the file and see if it attempted an operation that failed. If it is a filesystem operation I could add a better implementation for that.

**Comment by aznowicz** [comment] 2016-05-04 06:11
Hi,
Yes this is mpd that runs 100%.
If i kill the mpd process, and restart it after, there is a message on stderr like the following :
**flac: FLAC__STREAM_DECODER_SEEK_ERROR**

You will see it in the attached files.
I cut a flac to 10 seconds and ran mpd like mentioned in your post.
I waited 5-6 seconds before killing with Ctrl-C the mpd process.

[mpd-stderr.txt](https://github.com/hzeller/folve/files/248197/mpd-stderr.txt)
[strace-mpd.txt](https://github.com/hzeller/folve/files/248198/strace-mpd.txt)

**Comment by aznowicz** [comment] 2016-05-05 22:30
Hello,
I just installed latest Debian (jessy) on the same hardware.
No problem with this distro, using mpd version 0.19.1.
I may stick with this one, i'm a Arch fan but for this application, i need stability...
Will try to compile 0.19.1 on Arch, to confirm this is a mpd-related problem.
Thank you again for this amazing software. I'm doing 3-way active filtering with EQ, phase linearization for any resolution (no resampling). Quite happy with it !

**Comment by hzeller** [comment] 2017-08-07 06:59
So I could reproduce something with a newer version of libsnd (which is one of the libraries folve is using). It turns out, that in that case writing the flac-file didn't work as it gets hung up on having written the header already.

Fixed it in libsnd and sent a pull request upstream.
https://github.com/erikd/libsndfile/pull/307

**Comment by hzeller** [comment] 2017-08-10 15:41
It could also be that `mpd` just reads through the whole file instead of skipping to the next file. That of course forces folve to convert the whole file; The 100% CPU sounds like the symptom of that.

You can see this clearly in the folve webserver status page: you see that the progress encoding the file continues after you already pressed skip.

**Comment by hzeller** [comment] 2017-08-11 03:33
So I tried with MPD 0.19.15 and the current 0.20.9 with gmpc and mpc as client and couldn't reproduce the observed. Going next and previous does not create the 100% CPU issue but rather works as expected.
This is with libsndfile-1.0.29pre1 (current git) and current git folve on debian testing.

So I tend to think this was just an artifact of the arch distro you were using at the time. Closing for now, please re-open if there is some issue.

**Closed as completed by hzeller** 2017-08-11 03:33 UTC

**Comment by hzeller** [comment] 2019-11-09 17:22
^ I've added support that the position of the include file and library is extracted from `pkg-config`, so that two installation options would work.

(also, always make sure to run `ldconfig` when you compile and install libsndfile0
